cloud:
  aws:
    s3:
      bucket: a305-project-bucket
      region:
        static: ap-northeast-2
    stack.auto: false
    credentials:
      access-key: AKIA3FLDXCWKWW5EG2CJ
      secret-key: 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

spring:
  data:
    redis:
      host: localhost
      port: 6379
      password:

chatgpt:
  api:
    endpoint: https://api.openai.com/v1/chat/completions
    key: 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
