spring:
  profiles:
    active:
      - secret
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        #show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  security:
    oauth2:
      client:
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
        registration:
          kakao:
            client-id: 90bf89533551cd611c6591032a23caba
            client-secret: l7XW9E7wT7z8P2CtXB6pEyEk4Asl2rSo
            client-authentication-method: client_secret_post
            #테스트 이후에 uri 변경할것
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-name: kakao
            scope:
              - profile_nickname
              - profile_image

logging.level:
  org.hibernate.SQL: debug